version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: najibalyasyfi
      MONGO_INITDB_ROOT_PASSWORD: A!s3d4f5g6h7j8k9l0
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local
