version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: A!s3d4f5g6h7j8k9l0
      MYSQL_DATABASE: CAMS
      MYSQL_USER: najibalyasyfi
      MYSQL_PASSWORD: A!s3d4f5g6h7j8k9l0
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
